// packages/joint-vitest-vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { dia, shapes } from '@joint/core';

const canvas = ref<Element | null>(null);

const graph = new dia.Graph({}, {
  cellNamespace: shapes
});
const paper = new dia.Paper({
  model: graph,
  background: {
    color: '#F8F9FA'
  },
  frozen: true,
  async: true,
  sorting: dia.Paper.sorting.APPROX,
  cellViewNamespace: shapes
});

/*const scroller = new ui.PaperScroller({
  paper,
  autoResizePaper: true,
  cursor: 'grab'
});

scroller.render();*/

const rect = new shapes.standard.Rectangle({
  position: { x: 100, y: 100 },
  size: { width: 100, height: 50 },
  attrs: {
    label: {
      text: 'Hello World'
    }
  }
});

graph.addCell(rect);

onMounted(() => {
  canvas.value?.appendChild(paper.el);
  //canvas.value?.appendChild(scroller.el);
  //scroller.center();
  paper.unfreeze();
});
</script>

<template>
  <div class="canvas" ref="canvas"></div>
</template>

<style scoped>
.canvas {
  width: 100%;
  height: 100%;
}

.canvas:deep(.joint-paper) {
  border: 1px solid #a0a0a0;
}
</style>

// packages/joint-vitest-react/src/App.tsx
import React, { useEffect, useRef } from 'react';
import { dia, shapes } from '@joint/core';
import './App.scss';

function App() {

  const canvas: any = useRef(null);

  useEffect(() => {
    const graph = new dia.Graph({}, { cellNamespace: shapes });

    const paper = new dia.Paper({
        model: graph,
        background: {
          color: '#F8F9FA',
        },
        frozen: true,
        async: true,
        sorting: dia.Paper.sorting.APPROX,
        cellViewNamespace: shapes
    });

    canvas.current.appendChild(paper.el);

    /*const scroller = new ui.PaperScroller({
        paper,
        autoResizePaper: true,
        cursor: 'grab'
    });

    canvas.current.appendChild(scroller.el);
    scroller.render().center();*/

    const rect = new shapes.standard.Rectangle({
      position: { x: 100, y: 100 },
      size: { width: 100, height: 50 },
      attrs: {
          label: {
             text: 'Hello World'
         }
       }
    });

    graph.addCell(rect);
    paper.unfreeze();

    return () => {
        //scroller.remove();
        paper.remove();
    };
  }, []);

  return (
    <div className="canvas" ref={canvas}/>
  );

}

export default App;
